services:
  headscale:
    image: headscale/headscale:0.27.1
    container_name: headscale
    pull_policy: missing
    restart: always
    command: serve
    environment:
      - TZ=Europe/Istanbul
    expose:
      - 8080 #  Main server
      - 9090 #  Metrics
      - 50443 # GRPC
    ports:
      - 0.0.0.0:3478:3478/udp # stun
    volumes:
      - ./.docker/headscale/config/config.yaml:/etc/headscale/config.yaml:ro
      - ./.docker/headscale/data:/var/lib/headscale
      - headscale-socket:/var/run/headscale:rw
    networks:
      - traefik-network
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-network

      # Routers
      - traefik.http.routers.headscale.rule=Host(`${HEADSCALE_SERVER_HOSTNAME:?required}`)
      - traefik.http.routers.headscale.entrypoints=websecure
      - traefik.http.routers.headscale.tls.certresolver=le-cloudflare
      - traefik.http.routers.headscale.service=headscale

      # Services
      - traefik.http.services.headscale.loadbalancer.server.port=8080

      - me.tale.headplane.target=headscale
    healthcheck:
      test: [ "CMD", "headscale", "health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  headscale-console:
    image: ghcr.io/rickli-cloud/headscale-console:${HEADSCALE_CONSOLE_VERSION:-latest}
    container_name: headscale-console
    pull_policy: missing
    restart: always
    command: serve
    expose:
      - 3000
    volumes:
      - ./.docker/headscale/config/config.yaml:/etc/headscale/config.yaml:ro
    networks:
      - traefik-network
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-network

      # Routers
      - traefik.http.routers.headscale-console.rule=Host(`${HEADSCALE_SERVER_HOSTNAME:?required}`) && PathPrefix(`/console`)
      - traefik.http.routers.headscale-console.entrypoints=websecure
      - traefik.http.routers.headscale-console.tls.certresolver=le-cloudflare
      - traefik.http.routers.headscale-console.service=headscale-console

      # Middlewares
      - traefik.http.middlewares.headscale-console-rewrite.replacepathprefix.from=/console
      - traefik.http.middlewares.headscale-console-rewrite.replacepathprefix.to=/admin
      - traefik.http.routers.headscale-console.middlewares=headscale-console-rewrite

      # Services
      - traefik.http.services.headscale-console.loadbalancer.server.port=3000

  headscale-selfservice:
    image: ghcr.io/rickli-cloud/headscale-console:${HEADSCALE_CONSOLE_VERSION:-latest}
    container_name: headscale-selfservice
    pull_policy: missing
    restart: always
    command: selfservice --control-url https://${HEADSCALE_SERVER_HOSTNAME:?required}
    depends_on:
      headscale:
        condition: service_started
    volumes:
      - headscale-socket:/var/run/headscale:ro
      - selfservice-data:/data:rw

  headscale-policyservice:
    image: ghcr.io/rickli-cloud/headscale-console:${HEADSCALE_CONSOLE_VERSION:-latest}
    container_name: headscale-policyservice
    pull_policy: missing
    restart: always
    command: policyservice --control-url https://${HEADSCALE_SERVER_HOSTNAME:?required}
    depends_on:
      headscale:
        condition: service_started
    volumes:
      - headscale-socket:/var/run/headscale:ro
      - policyservice-data:/data:rw

  headplane:
    image: ghcr.io/tale/headplane:v0.6.1
    container_name: headplane
    restart: unless-stopped
    expose:
      - 3000
    volumes:
      - ./.docker/headplane/config/config.yaml:/etc/headplane/config.yaml
      - ./.docker/headplane/data/storage:/var/lib/headplane
      - ./.docker/headscale/config/config.yaml:/etc/headscale/config.yaml
      - ./.docker/headscale/config/dns_records.json:/etc/headscale/dns_records.json
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-network
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-network

      # Routers
      - traefik.http.routers.headplane.rule=Host(`${HEADSCALE_SERVER_HOSTNAME:?required}`) && PathPrefix(`/admin`)
      - traefik.http.routers.headplane.entrypoints=websecure
      - traefik.http.routers.headplane.tls.certresolver=le-cloudflare
      - traefik.http.routers.headplane.service=headplane

      # Services
      - traefik.http.services.headplane.loadbalancer.server.port=3000


volumes:
  selfservice-data:
    name: selfservice-data
  policyservice-data:
    name: policyservice-data
  headscale-socket:
    name: headscale-socket


networks:
  traefik-network:
    external: true
